### PR TITLE
Update Utility.coffee

### PR DESCRIPTION
**Pull request by ricpelo**
Take care of value.parameters to be undefined.

### CODE REVIEW

**Comment by ricpelo** [comment]
Fixes #2 .

**Comment by ghost** [comment]
Thanks for this, it will fix the problem in this package, but I'm afraid the root cause of this issue is somewhere in the base package. The `parameters` property should never be `undefined` as if there are no parameters, it should be an empty array. However, I've not been able to reproduce the issue since it was reported. It would be useful if you could provide a codebase or testcode where I could reproduce it, so I can track down the accompanying issue in the base package.

**Comment by ricpelo** [comment]
Thanks for the reply, @Gert-dev . Issue #2 contains a step-by-step guide in order to reproduce this issue. The following is a copy&paste of my comment in that issue report. Hope this helps:

[Enter steps to reproduce below:]
1. composer create-project --prefer-dist yiisoft/yii2-app-basic basic
2. cd basic
3. atom .
4. Open controllers/SiteController.php
5. Move mouse cursor over "behaviors()" method name on line 14.

**Atom Version**: 1.5.3
**System**: Ubuntu 14.04.4
**Thrown From**: [php-integrator-tooltips](https://github.com/Gert-dev/php-integrator-tooltips) package, v0.4.0

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /home/ricardo/.atom/packages/php-integrator-tooltips/lib/Utility.coffee:37

TypeError: Cannot read property 'length' of undefined
    at Object.module.exports.buildTooltipForFunction (/home/ricardo/.atom/packages/php-integrator-tooltips/lib/Utility.coffee:37:9)
    at FunctionDefinitionProvider.module.exports.FunctionDefinitionProvider.getTooltipForWord (/home/ricardo/.atom/packages/php-integrator-tooltips/lib/FunctionDefinitionProvider.coffee:38:24)
    at FunctionDefinitionProvider.module.exports.AbstractProvider.showPopoverFor (/home/ricardo/.atom/packages/php-integrator-tooltips/lib/AbstractProvider.coffee:139:24)
    at HTMLSpanElement.<anonymous> (/home/ricardo/.atom/packages/php-integrator-tooltips/lib/AbstractProvider.coffee:108:18)
    at HTMLDivElement.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -0:26.7.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:26.4.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:26.1.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:25.7.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:25.5.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:25.2.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:24.9.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:19.6.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:19.2.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:18.4.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -0:16.7.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:16.7.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:16.4.0 core:move-left (atom-text-editor.editor.is-focused)
 16x -0:16.2.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:00.5.0 click (atom-text-editor.editor.is-focused)
     -0:00.0 core:move-down (atom-text-editor.editor.is-focused)
```

### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "closeEmptyWindows": false,
    "disabledPackages": [
      "vim-mode"
    ],
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
atom-yii2, v0.4.0
git-diff-details, v0.22.0
keyboard-localization, v1.4.14
language-latex, v0.6.1
linter, v1.11.3
linter-php, v1.1.8
linter-phpcs, v1.3.0
linter-tidy, v2.1.0
minimap, v4.19.0
php-cs-fixer, v2.5.6
php-extract-method, v0.2.1
php-integrator-annotations, v0.3.0
php-integrator-autocomplete-plus, v0.5.2
php-integrator-base, v0.6.2
php-integrator-call-tips, v0.2.1
php-integrator-navigation, v0.5.0
php-integrator-tooltips, v0.4.0
symbols-tree-view, v0.11.0
tabs-to-spaces, v1.0.2
vim-modeline, v0.4.0

# Dev
No dev packages
```

Thanks again!

**Comment by ghost** [comment]
I'll close this since we (finally) got it sorted in #2.

**Pull request closed without merging**
